// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADSIhg84-ELrTANkL59bxaR-R11LUO9M0',
    appId: '1:249366528665:web:d36a8f75cc005d3df52e08',
    messagingSenderId: '249366528665',
    projectId: 'tbproject-424ac',
    authDomain: 'tbproject-424ac.firebaseapp.com',
    storageBucket: 'tbproject-424ac.firebasestorage.app',
    measurementId: 'G-YSYSBDX838',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1HHNQp8kTpGN5T8sXQ5hyqGxyMMLH_rc',
    appId: '1:249366528665:android:5e1c0075fc8f83eaf52e08',
    messagingSenderId: '249366528665',
    projectId: 'tbproject-424ac',
    storageBucket: 'tbproject-424ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl7V9KQX6RGP-daLW_becbmBu9qj1vDRg',
    appId: '1:249366528665:ios:70aad44c2035f187f52e08',
    messagingSenderId: '249366528665',
    projectId: 'tbproject-424ac',
    storageBucket: 'tbproject-424ac.firebasestorage.app',
    iosBundleId: 'com.example.kasirTokoBangunan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl7V9KQX6RGP-daLW_becbmBu9qj1vDRg',
    appId: '1:249366528665:ios:70aad44c2035f187f52e08',
    messagingSenderId: '249366528665',
    projectId: 'tbproject-424ac',
    storageBucket: 'tbproject-424ac.firebasestorage.app',
    iosBundleId: 'com.example.kasirTokoBangunan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADSIhg84-ELrTANkL59bxaR-R11LUO9M0',
    appId: '1:249366528665:web:c64432d409fa3597f52e08',
    messagingSenderId: '249366528665',
    projectId: 'tbproject-424ac',
    authDomain: 'tbproject-424ac.firebaseapp.com',
    storageBucket: 'tbproject-424ac.firebasestorage.app',
    measurementId: 'G-F3J3D2BDX1',
  );
}
